### ISSUE TITLE
Why there is no quantization of image when testing the TFLite model?

### ISSUE THREAD

**Issue by aizzaac** [Namburger/edgetpu-ssdlite-mobiledet-retrain#1]
Hi

I am studying the notebook. It seems there is no quantization when testing the TFLite model. Meanwhile there is one when testing the TensorFLow model. 

TensorFLow model ```.astype(np.uint8)```
```
test_image_path = [os.path.join('/content/test', 'image{}.jpg'.format(i)) for i in range(1, 6)]
for image_path in test_image_path:
  print('Evaluating:', image_path)
  image = Image.open(image_path)
  img_width, img_height = image.size
  image_np = np.array(image.getdata()).reshape((img_height, img_width, 3)).astype(np.uint8)
  # Run inference.
  output_dict = run_inference(detection_graph, image_np)
```

TFLite model
```
test_image_paths = [os.path.join('/content/test', 'image{}.jpg'.format(i)) for i in range(1, 6)]
for image_path in test_image_paths:
  print('Evaluating:', image_path)
  image = Image.open(image_path)
  image_width, image_height = image.size
  draw = ImageDraw.Draw(image)
  resized_image = image.resize((width, height))
  np_image = np.asarray(resized_image)
  input_tensor = np.expand_dims(np_image, axis=0)
  # Run inference
  boxes, classes, scores = run_inference(interpreter, input_tensor)
```

**Comment by Namburger** [comment]
It is because 
```
  image_np = np.array(image.getdata()).reshape((img_height, img_width, 3)).astype(np.uint8)
```
vs 
```
  image = Image.open(image_path)
  image_width, image_height = image.size
  draw = ImageDraw.Draw(image)
  resized_image = image.resize((width, height))
  np_image = np.asarray(resized_image)
```
The latter already cast the np_image as uint8 type so there is no need to do it explicitly. You can easily check this by adding this line:
```
  print(type(np_image[0][0][0]))
```

FYI, this has nothing to do with quantization, but rather the input type.

**Comment by aizzaac** [comment]
Ah, okey. I think it has already been casted because of the 2 last lines of this code:

![image](https://user-images.githubusercontent.com/68517348/96511676-61e29680-122d-11eb-9f3f-efc7f2647a70.png)

What is [0][0][0] doing?

**Comment by Namburger** [comment]
the last 2 lines of that code clearly just extracting the width and height, how does that related to what you are asking?
`[0][0][0]` is just accessing elements in a 3d array, that's cs101
