### ISSUE TITLE
Why all operations are not mapped to Edge TPU ?

### ISSUE THREAD

**Issue by pirazor** [Namburger/edgetpu-ssdlite-mobiledet-retrain#3]
I've not tested the speed on Coral USB accelerator, but I was curious why the custom operation could not be mapped to Edge TPU ? Correct me if I am wrong, but I remember the Edge TPU partitions the graph until an unsupported operation is seen and the remaining portion of the graph will be running on CPU.
![IMG_20201127_145830](https://user-images.githubusercontent.com/4476779/100481593-8b130400-30c2-11eb-9646-07cfb38f326d.jpg)

**Comment by Namburger** [comment]
@pirazor hey!
> the Edge TPU partitions the graph until an unsupported operation is seen and the remaining portion of the graph will be running on CPU

That's correct, but if you visualized the model using tools like[netron](https://github.com/lutzroeder/netron), you will have realized that the CPU op is actually the very last ops in this model. It is the post processing op that gives the model the outputs as described [here](https://www.tensorflow.org/lite/models/object_detection/overview). 
Without that you'll have a fully compatible model with the edgetpu, but you'll end up having to implements post processing yourself, which will happens on cpu anyways.
